---
- name: Setup Arch Linux Workstation
  hosts: all
  vars_files:
    - "main.yml"
  tasks:
    - name: "Include packages"
      ansible.builtin.include_vars:
        file: "packages.yml"

    - name: "Install basic packages"
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: Clone AwesomeWM Config
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.git:
        repo: "https://github.com/andreztz/awesome"
        dest: "{{ home }}/.config/awesome"
        update: "{{ sync_git_repo }}"

    - name: Clone Net Widgets
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.git:
        repo: "https://github.com/pltanton/net_widgets.git"
        dest: "{{ home }}/.config/awesome/net_widgets"
        update: "{{ sync_git_repo }}"

    - name: Clone Vicious Widgets
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.git:
        repo: "https://github.com/vicious-widgets/vicious.git"
        dest: "{{ home }}/.config/awesome/vicious"
        update: "{{ sync_git_repo }}"

    - name: Clone dotfiles
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.git:
        repo: "https://github.com/andreztz/dotfiles.git"
        dest: "{{ home }}/.dotfiles"
        update: "{{ sync_git_repo }}"

    - name: Clone tmux/tpm plugin manager
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ home }}/.tmux/plugins/tpm"
        update: "{{ sync_git_repo }}"

    - name: Clone Neovim config files
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.git:
        repo: "https://github.com/andreztz/editor.git"
        dest: "{{ home }}/.config/nvim"
        update: "{{ sync_git_repo }}"

    - name: Clone oh-my-zsh
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: "{{ home }}/.oh-my-zsh"
        update: "{{ sync_git_repo }}"

    - name: Create directory ~/.local/share/fonts
      become: true
      become_user: "{{ user_name }}"
      ansible.builtin.file:
        path: "{{ home }}/.local/share/fonts"
        state: directory
        mode: "0755"

    - name: Download Fonts
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.url | basename }}"
        mode: "0644"
      loop: "{{ font_list }}"

    - name: Unpack fonts to ~/.local/share/fonts
      ansible.builtin.unarchive:
        src: "/tmp/{{ item.url | basename }}"
        dest: "{{ home }}/.local/share/fonts"
        remote_src: true
      loop: "{{ font_list }}"

    - name: Apply dotfileis
      dotfiles:
        src: "{{ item }}"
        repo: "{{ home }}/.dotfiles"
        dest: "{{ home }}"
        state: present
      loop: "{{ dotfiles }}"

    - name: Install uv
      become: false
      become_user: "{{ user_name }}"
      ansible.builtin.shell: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/bin/uv"
